#!/usr/bin/python


import re
import sys
import subprocess
import os
import signal
import random


# Copied from http://stacyprowell.com/blog/2009/03/trapping-ctrlc-in-python/
class BreakHandler:
    '''
    Trap CTRL-C, set a flag, and keep going.  This is very useful for
    gracefully exiting database loops while simulating transactions.

    To use this, make an instance and then enable it.  You can check
    whether a break was trapped using the trapped property.

    # Create and enable a break handler.
    ih = BreakHandler()
    ih.enable()
    for x in big_set:
        complex_operation_1()
        complex_operation_2()
        complex_operation_3()
        # Check whether there was a break.
        if ih.trapped:
            # Stop the loop.
            break
    ih.disable()
    # Back to usual operation...
    '''

    def __init__(self, emphatic=9):
        '''
        Create a new break handler.

        @param emphatic: This is the number of times that the user must
                    press break to *disable* the handler.  If you press
                    break this number of times, the handler is automagically
                    disabled, and one more break will trigger an old
                    style keyboard interrupt.  The default is nine.  This
                    is a Good Idea, since if you happen to lose your
                    connection to the handler you can *still* disable it.
        '''
        self._count = 0
        self._enabled = False
        self._emphatic = emphatic
        self._oldhandler = None
        return

    def _reset(self):
        '''
        Reset the trapped status and count.  You should not need to use this
        directly; instead you can disable the handler and then re-enable it.
        This is better, in case someone presses CTRL-C during this operation.
        '''
        self._count = 0
        return

    def enable(self):
        '''
        Enable trapping of the break.  This action also resets the
        handler count and trapped properties.
        '''
        if not self._enabled:
            self._reset()
            self._enabled = True
            self._oldhandler = signal.signal(signal.SIGINT, self)
        return

    def disable(self):
        '''
        Disable trapping the break.  You can check whether a break
        was trapped using the count and trapped properties.
        '''
        if self._enabled:
            self._enabled = False
            signal.signal(signal.SIGINT, self._oldhandler)
            self._oldhandler = None
        return

    def __call__(self, signame, sf):
        '''
        An break just occurred.  Save information about it and keep
        going.
        '''
        self._count += 1
        # If we've exceeded the "emphatic" count disable this handler.
        if self._count >= self._emphatic:
            self.disable()
        return

    def __del__(self):
        '''
        Python is reclaiming this object, so make sure we are disabled.
        '''
        self.disable()
        return

    @property
    def count(self):
        '''
        The number of breaks trapped.
        '''
        return self._count

    @property
    def trapped(self):
        '''
        Whether a break was trapped.
        '''
        return self._count > 0


def hostname():
    """Return the short hostname of the machine."""
    return subprocess.Popen(["hostname", "-s"], stdout=subprocess.PIPE).communicate()[0].strip()
    

def main():

    out = subprocess.Popen(['ps', 'x', '-o', 'pid,command'], stdout=subprocess.PIPE).communicate()[0]
    processes_raw = out.split('\n')[1:-1]
    node_index = 1
    node_noconn = []
    node_conn = []

    for process_raw in processes_raw:
        process = process_raw.strip().split()
        #if len(process) < 2:
        #    print process
        #    continue
        pid = process[0]
        command = process[1]
        params = process[2:]
        if (command.endswith('beam') or command.endswith('beam.smp')):
            name = None
            name_type = None # '-name' or '-sname'
            cookie = None
            i = 0
            while i < len(params):
                param = params[i]
                if param in ('-name', '-sname'):
                    name = params[i + 1]
                    name_type = param
                    i += 1
                elif param == '-setcookie':
                    cookie = params[i + 1]
                    i += 1
                i += 1
            if None in (name, name_type):
                node_noconn.append(process_raw)
            else:
                erl_command = re.sub(r'(beam|beam.smp)$', 'erl', command)
                client_name = 'client_%s_%s' % (random.randint(0,10000), name)
                if name_type == '-sname':
                    name += '@' + hostname()
                start_cmd = [erl_command, name_type, client_name, '-remsh', name]
                if cookie is not None:
                    start_cmd += ['-setcookie', cookie]
                node_conn.append({'name': name,
                                  'cookie': cookie,
                                  'pid': pid,
                                  'start_cmd': start_cmd})

    if len(node_conn) > 0:
        print 'Available nodes: index name (cookie, pid)'
        print
        for i, node in enumerate(node_conn):
             print '    %s. %s (%s %s)' % (i + 1, node['name'], node['cookie'],
                                            node['pid'])
             #print '   ', node['start_cmd']

    if len(node_noconn) > 0:
        print '''
Cannot connect to the following nodes because node name is missing:'''
    for process in node_noconn:
        print ' ', process

    if len(node_conn) > 0:
        sys.stdout.write('''
Type the index of the node name to which you wish to connect or hit Enter to
cancel.
> ''')
        sys.stdout.flush()
    else:
        print 'No Erlang nodes found.'

    if len(node_conn) > 0:
        action = 'connect'
        line = sys.stdin.readline()
        node = None
        try:
            if line[0] == 'k':
                action = 'kill'
                line = line[1:]
            node = node_conn[int(line) - 1]
        except ValueError:
            pass
        except IndexError:
            pass

        if node is not None:
            if action == 'connect':
                bh = BreakHandler()
                bh.enable()
                print node['start_cmd']
                p = subprocess.Popen(node['start_cmd']).wait()
            elif action == 'kill':
                cmd = ['kill', str(node['pid'])]
                print cmd
                p = subprocess.Popen(cmd).wait()
                


if __name__ == '__main__':
    main()
